### ISSUE TITLE
Unsupported Metrics

### ISSUE THREAD

**Issue by v-shalimov** [berezhinskiy/ecoflow_exporter#16]
The list of unsupported metrics from the logs for my Delta 2, as you've asked:

- pd.icoBytes
- pd.reserved
- bms_emsStatus.bmsIsConnt
- inv.reserved
- mppt.res

**Comment by v-shalimov** [comment]
And, BTW, yes, you were absolutely right about zeroes in arrays:

- Skipping unsupported metric mppt.res: [0, 0, 0, 0, 0]
- Skipping unsupported metric inv.reserved: [0, 0, 0, 0, 0, 0, 0, 0]
- Skipping unsupported metric pd.icoBytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
- Skipping unsupported metric pd.reserved: [0, 0]
- Skipping unsupported metric bms_emsStatus.bmsIsConnt: [3, 0, 0]

So, only the Skipping bms_emsStatus.bmsIsConnt had something non-zero in the array

**Comment by berezhinskiy** [comment]
@v-shalimov It needs to be clarified what strictly this information provides and how to convert such arrays to the Prometheus format. So, I decided to [skip any arrays](https://github.com/berezhinskiy/ecoflow_exporter/blob/master/ecoflow_exporter.py#L228-L230) with warning message.
