### ISSUE TITLE
Support DELTA Max Grafana dashboard

### ISSUE THREAD

**Issue by alex-popov-tech** [berezhinskiy/ecoflow_exporter#17]
Hello, thank you for dashboard!

I have EcoFlow Max + extra battery, and it shows following
<img width="589" alt="CleanShot 2023-01-24 at 21 35 45@2x" src="https://user-images.githubusercontent.com/21224705/214391208-9838ed9a-8dc7-4c19-9572-9f309b469855.png">

can i somehow help with debugging or adding support for `max` version?

Note:

Events are there and seems to be processing 
<img width="1086" alt="CleanShot 2023-01-24 at 21 37 42@2x" src="https://user-images.githubusercontent.com/21224705/214391644-6480f1b0-aea7-4f76-b5bb-e76b367df29c.png">

**Comment by berezhinskiy** [comment]
Hi Alex, could you please post output of the following command:
```
curl http://<ecoflow_exporter_ip>:<ecoflow_exporter_port>/
```

**Comment by berezhinskiy** [comment]
@alex-popov-tech Also, you can check that Prometheus datasource works well on Grafana side: Configuration -> Data sources -> Prometheus -> scroll down and click "Save & test". You should see message "Data source is working"

**Comment by alex-popov-tech** [comment]
> @alex-popov-tech Also, you can check that Prometheus datasource works well on Grafana side: Configuration -> Data sources -> Prometheus -> scroll down and click "Save & test". You should see message "Data source is working"

Yes, i see that

> Hi Alex, could you please post output of the following command:

Sorry, but that image does not expose any ports, isn't it?

**Comment by berezhinskiy** [comment]
@alex-popov-tech Since Prometheus should talk directly to the exporter it should expose HTTP port. Right now I'm in the process of preparing another Quick Start guide with docker-compose examples. I decided to invest some time in that because most questions are not related to the exporter itself. People cannot just start using exporter. It is required to know general Prometheus and Grafana architecture and data flows. A detailed guide will save me lots of time in the future. Can you help me with the beta testing of such a guide? I believe it will solve your issue and will be so valuable for me. If so, here is a link to the branch: https://github.com/berezhinskiy/ecoflow_exporter/tree/feature/rich-quick-start-with-telegram-alerts/docker-compose

**Comment by alex-popov-tech** [comment]
@berezhinskiy will do!
Right now i have scheduled blackout, but tomorrow i will give it a try and try to provide feedback <3
Thank you!

**Comment by alex-popov-tech** [comment]
@berezhinskiy hey!
I checked out your branch and followed instructions, re-creating whole environment.
It works better 
<img width="1838" alt="CleanShot 2023-01-25 at 14 29 08@2x" src="https://user-images.githubusercontent.com/21224705/214563606-bd8b099f-caf6-4cf1-a914-fc33c9051169.png">
but for some reason some fields still missing the data 🤷🏻‍♂️ 

as for instructions - they were clear, now they are even simpler, the only thing im not understand is about alert service, but i did not use it before and did not think i need that, so i just deleted that service and it worked well

**Comment by berezhinskiy** [comment]
@alex-popov-tech Thanks. Regarding the missing data in the dashboard, it seems that Delta MAX is sending different values, like Delta Pro. You need to edit the dashboard and rename metrics as mentioned in #15  I suggest you contact @vbash and ask him to share his dashboard with you (json file). Let's see if the values for Max and Pro are the same. If so, I thought publishing multiple dashboards for the different models would be a good idea. 

@vbash looks ok for you?

**Comment by vbash** [comment]
Done. The file is attached to #15

**Comment by vbash** [comment]
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/6259008/214784951-74628afb-7361-44a8-891a-64662b7a9e2b.png">

**Comment by berezhinskiy** [comment]
@skabashnyuk As mentioned in README, the exporter converts the MQTT payload to Prometheus format. The exporter itself does not know anything about metrics names or EcoFlow models. It is much easy to adjust existing dashboards with different values than implement support for all existing models with their values in the source code. I've already updated the dashboard for DELTA Pro in the scope of #15 Once @alex-popov-tech will provide a dashboard for Max I will update it as well.

**Comment by alex-popov-tech** [comment]
hey @berezhinskiy , here is my version 
<img width="1847" alt="CleanShot 2023-01-31 at 17 40 46@2x" src="https://user-images.githubusercontent.com/21224705/21580665
[EcoFlow_MAX-1675179778316.json.zip](https://github.com/berezhinskiy/ecoflow_exporter/files/10548150/EcoFlow_MAX-1675179778316.json.zip)
0-e338e9fd-188a-4af8-9c36-365319319d6d.png">

**Comment by berezhinskiy** [comment]
> hey @berezhinskiy , here is my version <img alt="CleanShot 2023-01-31 at 17 40 46@2x" width="1847" src="https://user-images.githubusercontent.com/21224705/215806650-e338e9fd-188a-4af8-9c36-365319319d6d.png">
> 
> [EcoFlow_MAX-1675179778316.json.zip](https://github.com/berezhinskiy/ecoflow_exporter/files/10548150/EcoFlow_MAX-1675179778316.json.zip)

@alex-popov-tech Thanks for sharing the dashboard. As I see, the values for Max are the same as for Pro. I have already uploaded the updated dashboard revision, which supports it.

**Comment by berezhinskiy** [comment]
@skabashnyuk Please, import the dashboard from [grafana website](https://grafana.com/grafana/dashboards/17812-ecoflow/) It has some differences.
