### ISSUE TITLE
Ecoflow River 2 Max and Delta 2, works well

### ISSUE THREAD

**Issue by arturpilavetz** [berezhinskiy/ecoflow_exporter#23]
It works well, a bit of a misunderstanding with the .env file, that the credentials should be without any "" or <>. And for a lazy person, the command "docker compose up -d" must run inside a docker-compose folder.

![tg_image_1348863010](https://user-images.githubusercontent.com/86111307/217663627-f2ecacd2-b782-4e4b-a326-a3e008ebbc13.jpeg)

**Comment by berezhinskiy** [comment]
Thanks for the feedback.
