### ISSUE TITLE
Adding Solar Stats on the dashboard

### ISSUE THREAD

**Issue by vbash** [berezhinskiy/ecoflow_exporter#31]
I've played a bit with my solar panels and have a proposition to add some stats on the dashboard:
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/6259008/226693210-467ef583-5eb5-4143-9066-0cee9491f900.png">

I can share my dashboard json to pick those stat panels

**Comment by vbash** [comment]
Let me know if it makes sense to add it to the existing dashboard or I can create a separate solar-oriented dashboard.

**Comment by berezhinskiy** [comment]
@vbash Please, share your json file. I will add a separate section to the current dashboard.

**Comment by vbash** [comment]
[EcoFlow-1679587037094.json.zip](https://github.com/berezhinskiy/ecoflow_exporter/files/11053005/EcoFlow-1679587037094.json.zip)

Please ignore the self-sustainability blocks for now. It's experimental.
<img width="1731" alt="image" src="https://user-images.githubusercontent.com/6259008/227262032-25f51dcc-39a1-42e6-916d-6c92ff8cfa7b.png">

**Comment by berezhinskiy** [comment]
[rev9](https://grafana.com/api/dashboards/17812/revisions/9/download) now includes MPPT
