### ISSUE TITLE
Recommendation for monitoring multiple Ecoflow devices

### ISSUE THREAD

**Issue by Jiriteach** [berezhinskiy/ecoflow_exporter#36]
Hi - What would be the recommendation to monitor multiple Ecoflow River's? Just run multiple containers?

Thanks for the great work!

Thanks

**Comment by berezhinskiy** [comment]
@Jiriteach, indeed, you can achieve this by launching multiple containers, each with its own distinct ID. This will enable you to seamlessly switch between various devices on the Grafana dashboard.

**Comment by scamianbas** [comment]
> @Jiriteach, indeed, you can achieve this by launching multiple containers, each with its own distinct ID. This will enable you to seamlessly switch between various devices on the Grafana dashboard.

@berezhinskiy Hi, could you please give an example ? I duplicated the ecoflow_exporter container but it is not displayed in Grafana dashboard, thanks :)
