### ISSUE TITLE
Проблема при установке

### ISSUE THREAD

**Issue by owerrride** [berezhinskiy/ecoflow_exporter#44]
Доброго времени суток, подскажите пожалуйста как решить проблему, столкнулся при установке:
![285137782-cf839602-e880-4904-a49f-0d73ffeee30e](https://github.com/berezhinskiy/ecoflow_exporter/assets/115143645/6f1d4202-8c8a-42e0-a56e-7393fbb69a6d)

Система: Unraid 6.12.4
Заранее благодарен

**Comment by berezhinskiy** [comment]
@owerrride Where are you from?

**Comment by owerrride** [comment]
![1](https://github.com/berezhinskiy/ecoflow_exporter/assets/115143645/cf839602-e880-4904-a49f-0d73ffeee30e)

**Comment by berezhinskiy** [comment]
@owerrride Please take note of the following:

1. GitHub is a global community. Please be respectful and use international language.
2. Ensure the concealment of your login/password.

Regarding your initial inquiry, the response is straightforward: port 9090 is already in use on your host operating system.

**Comment by owerrride** [comment]
> Regarding your initial inquiry, the response is straightforward: port 9090 is already in use on your host operating system.

Thank you. But i change port from 9090 to 9200 in command for start container, This is not enough?

**Comment by berezhinskiy** [comment]
@owerrride Why are you using network type `host`?

**Comment by owerrride** [comment]
> Why are you using network type `host`?

o, thank you! I am understand  =)
