### ISSUE TITLE
How to monitor multiple Ecoflows ?

### ISSUE THREAD

**Issue by scamianbas** [berezhinskiy/ecoflow_exporter#50]
Hello,
how to monitor multiple Ecoflows and have their serial number available in the dropdown list in Grafana dashboard ?
I did try a lot of things suggested here but nothing works.
Thank you very much

**Comment by berezhinskiy** [comment]
Hi @scamianbas, to accomplish this, simply launch an additional Docker instance on another port with the corresponding device ID. Additionally, include one more job in the Prometheus `scrape_configs`

**Comment by scamianbas** [comment]
Hi @berezhinskiy ,

do you mean by modifying compose.yaml like this:
![image](https://github.com/berezhinskiy/ecoflow_exporter/assets/3215795/45403c5f-b6ca-4ea4-bf6b-05e77fede217)
and then prometheus.yaml like this:
![image](https://github.com/berezhinskiy/ecoflow_exporter/assets/3215795/58bab43d-d36b-4f14-95ee-963abe2f9e66)

Thank you very much

**Comment by scamianbas** [comment]
Thanks @berezhinskiy it works ! :)
Notice that **{device="$device"}** should be appended after each metric ;)
